// ============================================================
//  RUNTIME WORKER ASSETS (M2a, repository split)
//  The Pyodide worker and the grep regex worker are RUNTIME assets.
//  Their sources live here as string modules — never in a product
//  page, never in a DOM element, never fetched from elsewhere.
//  Hosts pass them to createRuntime({ workerAssets }) (or to
//  createPythonRuntime / the grep session in direct tests).
//
//  Migrated from index.html @ 83fdfbb (PR #4 head), CRLF normalized
//  to LF. The per-line JSON string form is mechanical: every source
//  line maps to exactly one entry, so diffs stay reviewable and no
//  escape (backtick, backslash) can corrupt the payload.
// ============================================================
export const PY_WORKER_SOURCE = [
  "",
  "// ============================================================",
  "//  PYODIDE WORKER  (protocol v3 — in-memory bootstrap)",
  "//  Executes Python against an in-memory mirror of the VFS data",
  "//  mounts and reports back stdout / stderr / tracebacks / changed",
  "//  files+dirs (ABSOLUTE paths).",
  "//",
  "//  AUTHORITY MODEL (F04b): this worker is created by the strict-CSP",
  "//  creator iframe (src/shell.js — see PY_CREATOR_CSP), so the BROWSER",
  "//  enforces \"no network egress\" on it (connect-src 'none', script-src",
  "//  without any loadable origin, worker-src blob:). Pyodide therefore",
  "//  cannot bootstrap from the CDN inside this worker — the TRUSTED",
  "//  harness (the page) fetches the FIXED asset set and delivers the",
  "//  bytes by postMessage. The worker boots Pyodide ENTIRELY from",
  "//  memory: pyodide.js / pyodide.asm.js are eval'd from text (never",
  "//  importScripts), and every fetch the loader makes (lock file, wasm,",
  "//  stdlib zip, package wheels) is served by a bootstrap-only",
  "//  in-memory resolver that fail-closes on every URL it does not hold",
  "//  EXACTLY (no path or query variation, no fallback to the native",
  "//  fetch, no CDN). After bootstrap the resolver's asset map is",
  "//  dropped and the F04a JS lockdown is applied as defense-in-depth —",
  "//  the browser policy remains the authoritative boundary either way.",
  "//",
  "//  Message in:  { id, cmd: 'bootstrap',",
  "//                 assets: { <name>: { text | buffer, mime } }",
  "//                 extensionModules?: [",
  "//                   { pluginId, files: { relPath: text },",
  "//                     imports: [module] }                    (LEGACY SYNTHETIC",
  "//                                     COMPOSITION PATH — source text, not TPR)",
  "//                 | { pluginId, wheels: [{ filename, format, size,",
  "//                                          sha256, bytes }],",
  "//                     imports: [module] } ]  (TPR v1A verified wheel payload,",
  "//                                   offline-installed before READY)",
  "//               { id, cmd: 'run', code, cwd,",
  "//                 mounts: [{ root, readOnly,",
  "//                            files: [{ path(ABS), b64 }],",
  "//                            directories: [ABS] }] }",
  "//  Boot out:    { id, type: 'boot', status: 'locked' }",
  "//             | { id, type: 'boot', error }",
  "//  Status out:  { id, type: 'status', status: 'loading' | 'ready' }",
  "//  Result out:  { id, type: 'result', stdout, stderr, error,",
  "//                 files: [{ path(ABS), b64 }], deleted: [ABS files],",
  "//                 createdDirs: [ABS], deletedDirs: [ABS],",
  "//                 uncollectedFiles: [ABS],",
  "//                 stdoutTruncated, stderrTruncated }",
  "//  `deleted` is FILES ONLY; directory creates/removals are reported in",
  "//  their own fields (createdDirs parent-first, deletedDirs child-first).",
  "// ============================================================",
  "",
  "// Virtual origin the resolver answers for. `.invalid` is a reserved TLD",
  "// that can never resolve; the exact-URL keys mean a typo'd or tampered",
  "// URL simply fails closed. No request for this origin can leave the",
  "// worker even if the resolver were bypassed — the creator CSP already",
  "// blocks every real fetch.",
  "const VIRTUAL_BASE = 'https://locus-bootstrap.invalid/';",
  "",
  "// Harness-owned runtime packages: the ONLY Pyodide packages the worker",
  "// ever installs, ONCE, during bootstrap and ALWAYS before user code",
  "// exists. What gets installed is a code-auditable harness decision — never",
  "// a side effect of a model-generated import (user-driven",
  "// loadPackagesFromImports is deliberately not part of this protocol).",
  "const PYTHON_RUNTIME_PACKAGES = ['pandas'];",
  "",
  "let py = null;",
  "let pyodideLoading = null;",
  "// Bootstrap state machine: 'cold' -> 'booting' -> 'locked'. User code",
  "// only ever executes in the 'locked' phase, i.e. after the interpreter,",
  "// the declared package set AND the network lockdown are all in place.",
  "let bootPhase = 'cold';",
  "// Set the moment a lockdown application is attempted: once true, a failed",
  "// bootstrap leaves the worker PERMANENTLY failed (its own bootstrap",
  "// primitives are no longer pristine, so a same-worker retry would run user",
  "// code half-locked). The worker then self-destructs and the shell rebuilds.",
  "let lockdownAttempted = false;",
  "",
  "// Bootstrap assets, delivered by the trusted harness (cmd: 'bootstrap').",
  "// Held until the boot succeeds or fails permanently; dropped on lock so",
  "// user code can never treat them as a resource oracle.",
  "let receivedAssets = null;",
  "let assetsWaiter = null;",
  "",
  "// Trusted-harness plugin payloads (Capability Composition v1 / TPR v1A),",
  "// delivered WITH the bootstrap message. Two shapes:",
  "//   - { pluginId, files: { relPath: text }, imports }  — LEGACY SYNTHETIC",
  "//     COMPOSITION PATH: source text written into site-packages. Not Trusted",
  "//     Plugin Runtime artifact delivery (V1B retires/isolates it).",
  "//   - { pluginId, wheels: [{ filename, format, size, sha256, bytes }],",
  "//     imports }  — TRUSTED WHEEL PAYLOAD: exact verified wheel bytes,",
  "//     installed OFFLINE (micropip + emfs: + deps=False) before READY.",
  "// Installed after the declared runtime package set (and, for wheels, after",
  "// the fixed installer closure) and BEFORE the network lockdown, so an",
  "// enabled plugin's import is an ordinary import of pre-installed code —",
  "// never a lazy install, never a runtime download, never user-driven.",
  "let receivedExtensions = [];",
  "",
  "function awaitAssets() {",
  "  if (receivedAssets) return Promise.resolve(receivedAssets);",
  "  if (!assetsWaiter) {",
  "    assetsWaiter = new Promise((resolve) => { assetsResolve = resolve; });",
  "  }",
  "  return assetsWaiter;",
  "}",
  "let assetsResolve = null;",
  "",
  "// ---- bootstrap-only in-memory asset resolver ----",
  "// Installed for the bootstrap window ONLY. Serves EXACTLY the URLs it",
  "// holds: full-string key match against VIRTUAL_BASE + name — no path",
  "// normalization, no query tolerance, no delegation to the native fetch.",
  "// Unknown URL: reject (fail closed). After the package set installs, the",
  "// asset map is dropped; the F04a lockdown then replaces the fetch slot",
  "// with the user-facing denial.",
  "let bootstrapAssets = null;",
  "",
  "function installBootstrapResolver(assets) {",
  "  bootstrapAssets = {};",
  "  for (const name of Object.keys(assets || {})) {",
  "    bootstrapAssets[VIRTUAL_BASE + name] = assets[name];",
  "  }",
  "  self.fetch = function (url) {",
  "    const u = String((url && url.url) || url);",
  "    const hit = bootstrapAssets && bootstrapAssets[u];",
  "    if (!hit) {",
  "      return Promise.reject(new TypeError(",
  "        'Locus Python bootstrap: no in-memory asset for ' + u));",
  "    }",
  "    const body = hit.text !== undefined ? hit.text : hit.buffer;",
  "    return Promise.resolve(new Response(body, {",
  "      status: 200,",
  "      headers: { 'content-type': hit.mime || 'application/octet-stream' },",
  "    }));",
  "  };",
  "}",
  "",
  "function textAsset(assets, name) {",
  "  const a = assets[name];",
  "  if (!a || typeof a.text !== 'string') {",
  "    throw new Error('Locus Python bootstrap: missing text asset: ' + name);",
  "  }",
  "  return a.text;",
  "}",
  "",
  "// ---- user-code authority boundary (denies, not a bridge) ----",
  "// Model-generated Python is LOCAL computation + filesystem. HTTP/HTTPS",
  "// belongs to the shell `curl` command, where NetworkRuntime owns",
  "// transport, approval and bounds. These denials are the technical",
  "// boundary; system-prompt wording only documents it.",
  "function denyUserNetwork() {",
  "  throw new Error('Python network access is disabled in Locus; use the shell curl command for HTTP/HTTPS');",
  "}",
  "function denyRuntimeBootstrap() {",
  "  throw new Error('Python package loading is controlled by the Locus runtime; declared runtime packages are provided automatically');",
  "}",
  "",
  "// A denied primitive is a callable whose every USE — call or construct —",
  "// raises the same bounded denial. Property READS stay readable: Pyodide's",
  "// own object introspection probes these global slots generically",
  "// (filteredHasKey while wrapping globalThis for the `js` module) and must",
  "// not explode, and a denied fetch's .call/.bind resolve to ordinary methods",
  "// whose invocation still routes through the denied [[Call]]. The ONE read",
  "// that would rebuild an escape hatch — .constructor, which hands back the",
  "// pristine Function intrinsic — is denied.",
  "function makeDenied() {",
  "  const denied = function () { denyUserNetwork(); };",
  "  try { Object.defineProperty(denied, '__locusNetworkDenied', { value: true }); } catch (e) {}",
  "  return new Proxy(denied, {",
  "    apply() { denyUserNetwork(); },",
  "    construct() { denyUserNetwork(); },",
  "    get(target, prop) {",
  "      if (prop === 'constructor') denyUserNetwork();",
  "      const v = target[prop];",
  "      return typeof v === 'function' ? v.bind(target) : v;",
  "    },",
  "  });",
  "}",
  "",
  "// Worker-global network and dynamic-execution primitives denied to user",
  "// code. Names this browser does not define are skipped (nothing to",
  "// lock); the REQUIRED set below must come out locked or bootstrap fails",
  "// closed — the worker never runs Python half-locked. `eval` is denied",
  "// because reachable dynamic-JS execution would otherwise rebuild network",
  "// primitives (js.eval / run_js) — Pyodide's own run_js routes through",
  "// js.eval, so it dies with it.",
  "//",
  "// The global `Function` constructor stays native ON PURPOSE: Pyodide's",
  "// own glue needs it (runPythonAsync breaks without it) and F04b's",
  "// boundary does NOT rest on denying compute. Dynamic JS built via",
  "// js.Function or any native function's .constructor still executes —",
  "// but inside this worker the BROWSER's strict CSP (inherited from the",
  "// creator iframe) makes every network act it could attempt",
  "// (fetch/dynamic import/importScripts/nested workers) fail at the",
  "// platform level with ZERO requests. F04a lockdown + browser policy:",
  "// the JS layer is defense-in-depth, the CSP is the authority.",
  "const DENY_NAMES = ['fetch', 'XMLHttpRequest', 'WebSocket', 'EventSource',",
  "  'WebTransport', 'Worker', 'SharedWorker', 'RTCPeerConnection',",
  "  'importScripts', 'caches', 'fetchLater', 'eval', 'loadPyodide'];",
  "const REQUIRED_LOCKED = ['fetch', 'XMLHttpRequest', 'WebSocket', 'importScripts', 'eval', 'loadPyodide'];",
  "",
  "// EVERY object in the prototype chain of `obj` that OWNS `name` as an own",
  "// property. WHICH level owns a given primitive differs between engines and",
  "// browser versions (audited Chrome 153 worker: fetch/importScripts/caches/",
  "// timers live on WorkerGlobalScope.prototype, XHR/WebSocket/Worker on the",
  "// global instance itself) — locking only the nearest owner leaves the",
  "// native primitive reachable one hop up the chain",
  "// (Object.getPrototypeOf(self).fetch was a working native fetch — F04a-A1).",
  "function ownersOf(obj, name) {",
  "  const owners = [];",
  "  let cur = obj;",
  "  while (cur) {",
  "    if (Object.prototype.hasOwnProperty.call(cur, name)) owners.push(cur);",
  "    cur = Object.getPrototypeOf(cur);",
  "  }",
  "  return owners;",
  "}",
  "",
  "function applyNetworkLockdown(instance) {",
  "  const g = globalThis;",
  "  for (const name of DENY_NAMES) {",
  "    if (!(name in g)) continue; // absent in this browser: nothing to lock",
  "    const denied = makeDenied();",
  "    // Lock EVERY prototype-chain level that owns the name with the SAME",
  "    // denied instance: user Python reads through self, but the ORIGINAL",
  "    // accessor lives further up, and Object.getPrototypeOf(js) must hand",
  "    // back the denial too — not a pristine native function. A level whose",
  "    // slot cannot be redefined throws here, which fails the whole",
  "    // bootstrap (fail-closed: the worker self-destructs and the shell",
  "    // rebuilds — Python never runs half-locked).",
  "    for (const owner of ownersOf(g, name)) {",
  "      Object.defineProperty(owner, name, { value: denied, writable: false, configurable: false });",
  "    }",
  "  }",
  "  // F04b: the Function/.constructor reconstruction path is closed by the",
  "  // creator iframe's CSP, not by denying the intrinsic (denying Function or",
  "  // Function.prototype.constructor breaks Pyodide's own interop — its JS",
  "  // glue identity-checks .constructor while crossing the PyProxy boundary",
  "  // and runPythonAsync then fails with \"globals must be a real dict\").",
  "  // A reconstructed Function still executes local compute; every network",
  "  // act it could attempt is blocked by the browser with ZERO requests",
  "  // (pinned by tests/e2e-python-browser-authority.cjs and the flipped",
  "  // F04a-R1 assertions in tests/e2e-python-authority.cjs).",
  "  // String-compile timers are eval in disguise (\"code\" handlers). Real",
  "  // function handlers keep working (Pyodide/Emscripten schedule functions).",
  "  // The SAME safe wrapper is installed at EVERY prototype-chain level that",
  "  // owns the timer — a shadow on the global alone leaves the native timer",
  "  // one hop up (p2.setInterval(\"import('…')\", 0) was a real escape).",
  "  for (const timer of ['setTimeout', 'setInterval']) {",
  "    if (!(timer in g)) continue;",
  "    const orig = typeof g[timer] === 'function' ? g[timer].bind(g) : null;",
  "    if (!orig) continue;",
  "    const safe = function (handler) {",
  "      if (typeof handler !== 'function') denyUserNetwork();",
  "      return orig.apply(null, arguments);",
  "    };",
  "    try { Object.defineProperty(safe, '__locusTimerSafe', { value: true }); } catch (e) {}",
  "    for (const owner of ownersOf(g, timer)) {",
  "      Object.defineProperty(owner, timer, { value: safe, writable: false, configurable: false });",
  "    }",
  "  }",
  "  // Forward defense (F04a-A5): navigator itself stays available (Pyodide",
  "  // and honest user code read navigator.userAgent etc.), but a sendBeacon",
  "  // anywhere on the navigator's prototype chain is a direct POST escape —",
  "  // lock it with the same walk. Browsers whose worker navigator has no",
  "  // sendBeacon (audited Chrome 153): nothing to do, skipped honestly.",
  "  const nav = g.navigator;",
  "  if (nav && 'sendBeacon' in nav) {",
  "    const deniedBeacon = makeDenied();",
  "    for (const owner of ownersOf(nav, 'sendBeacon')) {",
  "      Object.defineProperty(owner, 'sendBeacon', { value: deniedBeacon, writable: false, configurable: false });",
  "    }",
  "  }",
  "  // Event-handler ATTRIBUTES compile assigned strings as function bodies",
  "  // (self.onmessage = \"import('https://…')\" is remote JS execution). Lock",
  "  // the slots at their current values — the worker's own handler stays. A",
  "  // slot that cannot be redefined throws here, which fails the whole",
  "  // bootstrap (fail-closed: the same contract as the primitive levels —",
  "  // the worker self-destructs and the shell rebuilds; Python never runs",
  "  // half-locked). Then sweep the PROTOTYPE chain: a level that owns the",
  "  // attribute as a WebIDL accessor (get/set) gets a set-throws accessor",
  "  // instead — an own-slot lock does not reach a prototype setter. Audited",
  "  // Chrome 153 exposes no such descriptor on the worker scope prototypes,",
  "  // so this is forward defense: absent descriptors are skipped honestly,",
  "  // and a level that IS found but cannot be redefined throws (fail-closed).",
  "  for (const handler of ['onmessage', 'onmessageerror', 'onerror', 'onlanguagechange',",
  "    'onoffline', 'ononline', 'onrejectionhandled', 'onunhandledrejection']) {",
  "    if (!(handler in g)) continue;",
  "    Object.defineProperty(g, handler, { value: g[handler], writable: false, configurable: false });",
  "    for (const owner of ownersOf(Object.getPrototypeOf(g), handler)) {",
  "      const d = Object.getOwnPropertyDescriptor(owner, handler);",
  "      if (!d || typeof d.set !== 'function') continue;",
  "      Object.defineProperty(owner, handler, {",
  "        get() { return undefined; },",
  "        set() { denyUserNetwork(); },",
  "        configurable: false,",
  "      });",
  "    }",
  "  }",
  "  // Fail-closed self-check, extended to the prototype chain (F04a-A1):",
  "  // every REQUIRED primitive must be the denial at the chain-resolved slot",
  "  // AND at every level that owns it; the timers must be the safe wrapper at",
  "  // every owning level; a present sendBeacon must be denied. ANY gap throws",
  "  // — the worker is then permanently failed and self-destructs (the shell",
  "  // rebuilds a fresh one). Python never runs half-locked.",
  "  for (const name of REQUIRED_LOCKED) {",
  "    const v = g[name];",
  "    if (!v || v.__locusNetworkDenied !== true) {",
  "      throw new Error('Python worker failed to apply the network lockdown');",
  "    }",
  "    for (const owner of ownersOf(g, name)) {",
  "      const d = Object.getOwnPropertyDescriptor(owner, name);",
  "      if (!d || !d.value || d.value.__locusNetworkDenied !== true) {",
  "        throw new Error('Python worker failed to apply the network lockdown');",
  "      }",
  "    }",
  "  }",
  "  for (const timer of ['setTimeout', 'setInterval']) {",
  "    if (!(timer in g)) continue;",
  "    for (const owner of ownersOf(g, timer)) {",
  "      const d = Object.getOwnPropertyDescriptor(owner, timer);",
  "      if (!d || !d.value || d.value.__locusTimerSafe !== true) {",
  "        throw new Error('Python worker failed to apply the network lockdown');",
  "      }",
  "    }",
  "  }",
  "  if (g.navigator && 'sendBeacon' in g.navigator) {",
  "    for (const owner of ownersOf(g.navigator, 'sendBeacon')) {",
  "      const d = Object.getOwnPropertyDescriptor(owner, 'sendBeacon');",
  "      if (!d || !d.value || d.value.__locusNetworkDenied !== true) {",
  "        throw new Error('Python worker failed to apply the network lockdown');",
  "      }",
  "    }",
  "  }",
  "  // The bootstrap package loader must not be re-enterable from user code:",
  "  // pyodide.loadPackage / Python-side loadPackagesFromImports route here.",
  "  const loaderDenial = function () { denyRuntimeBootstrap(); };",
  "  for (const loader of ['loadPackage', 'loadPackagesFromImports']) {",
  "    Object.defineProperty(instance, loader, { value: loaderDenial, writable: false, configurable: false });",
  "  }",
  "}",
  "",
  "// ---- TPR v1A: worker-side wheel identity re-verification -----------------",
  "// The trusted Harness validated payload shape and metadata/bytes agreement",
  "// before the boot send, and the bytes traveled by structured clone — but the",
  "// worker NEVER trusts the channel: byte identity (exact size + SHA-256) is",
  "// re-proved here against the harness-declared metadata before anything is",
  "// written or installed. WebCrypto subtle is REQUIRED (same rule as the F04c",
  "// page-side asset gate): a context that cannot verify fails the boot closed.",
  "// A mismatch throws, which fails the WHOLE boot: no install, no smoke, no",
  "// READY. Error text names plugin id, artifact filename and fault category —",
  "// never the raw bytes.",
  "async function sha256HexOfBytes(bytes) {",
  "  if (typeof crypto === 'undefined' || !crypto.subtle",
  "      || typeof crypto.subtle.digest !== 'function') {",
  "    return null;",
  "  }",
  "  const digest = await crypto.subtle.digest('SHA-256', bytes);",
  "  const view = new Uint8Array(digest);",
  "  let hex = '';",
  "  for (let i = 0; i < view.length; i++) hex += (view[i] < 16 ? '0' : '') + view[i].toString(16);",
  "  return hex;",
  "}",
  "",
  "async function verifyWheelArtifact(mod, wheel) {",
  "  const bytes = wheel && wheel.bytes;",
  "  const received = bytes && bytes.byteLength;",
  "  if (!(bytes instanceof Uint8Array) || received !== wheel.size) {",
  "    throw new Error('Locus plugin install: artifact size mismatch: plugin ' + mod.pluginId",
  "      + ', artifact ' + (wheel && wheel.filename) + ' (declared ' + (wheel && wheel.size)",
  "      + ' bytes, received ' + received + ')');",
  "  }",
  "  const hex = await sha256HexOfBytes(bytes);",
  "  if (hex === null) {",
  "    throw new Error('Locus plugin install: artifact integrity unavailable (WebCrypto subtle missing): plugin '",
  "      + mod.pluginId + ', artifact ' + wheel.filename);",
  "  }",
  "  if (hex !== wheel.sha256) {",
  "    throw new Error('Locus plugin install: artifact sha256 mismatch: plugin ' + mod.pluginId",
  "      + ', artifact ' + wheel.filename);",
  "  }",
  "  return bytes;",
  "}",
  "",
  "// ---- TPR v1A: offline wheel install --------------------------------------",
  "// Harness-derived scratch path only: /tmp/locus-plugin-artifacts/<sha256>/",
  "// <filename>. The sha256 segment comes from the verified digest, the",
  "// filename from the main-thread basename validation — no model path input",
  "// ever reaches this code. The scratch file is interpreter bootstrap scratch:",
  "// NEVER a /mnt/workspace path, NEVER a Locus VFS durable file. It is removed",
  "// right after install (best-effort empty-dir cleanup) in every outcome.",
  "async function installWheelModule(instance, mod) {",
  "  for (const wheel of mod.wheels) {",
  "    const bytes = await verifyWheelArtifact(mod, wheel);",
  "    const dir = '/tmp/locus-plugin-artifacts/' + wheel.sha256;",
  "    const full = dir + '/' + wheel.filename;",
  "    instance.FS.mkdirTree(dir);",
  "    instance.FS.writeFile(full, bytes);",
  "    try {",
  "      // OFFLINE install: micropip reads the wheel straight out of the",
  "      // worker's Emscripten FS (its emfs: scheme is a plain local read) and",
  "      // deps=False is the Package v1 contract — exactly one wheel, no",
  "      // dependency closure, no package index, no network anywhere.",
  "      await instance.runPythonAsync(",
  "        'import micropip\\nawait micropip.install(\"emfs:' + full + '\", deps=False)');",
  "    } catch (e) {",
  "      throw new Error('Locus plugin install: offline wheel install failed: plugin ' + mod.pluginId",
  "        + ', artifact ' + wheel.filename + ': ' + String(e && e.message ? e.message : e));",
  "    } finally {",
  "      try { instance.FS.unlink(full); } catch (e) {}",
  "      try { instance.FS.rmdir(dir); } catch (e) {} // only succeeds when empty",
  "    }",
  "  }",
  "}",
  "",
  "// Retire the bootstrap-only installer before READY. The remote fetch path is",
  "// already dead twice over (F04a fetch denial + creator CSP), but a user-",
  "// phase micropip.install could still act as a LOCAL package loader (install",
  "// a wheel sitting in the mirrored workspace into the live interpreter).",
  "// Package loading is Harness-controlled, so after the trusted installs the",
  "// installer entry points become denials. `import micropip` itself stays",
  "// importable — no import-system damage, no hidden semantics.",
  "async function neuterBootstrapInstaller(instance) {",
  "  try {",
  "    await instance.runPythonAsync([",
  "      'import micropip as _locus_micropip',",
  "      'def _locus_install_denied(*_args, **_kwargs):',",
  "      '    raise RuntimeError(\"Python package installation is controlled by the Locus runtime; plugins are installed by the trusted harness before READY\")',",
  "      '_locus_micropip.install = _locus_install_denied',",
  "      '_locus_micropip.add_mock_package = _locus_install_denied',",
  "      '_locus_micropip.remove_mock_package = _locus_install_denied',",
  "    ].join('\\n'));",
  "  } catch (e) {",
  "    throw new Error('Locus plugin install: could not retire the bootstrap installer: '",
  "      + String(e && e.message ? e.message : e));",
  "  }",
  "}",
  "",
  "// ---- plugin payload install + smoke import ----",
  "// Runs in the TRUSTED harness window: after the declared package set (and",
  "// the fixed installer closure for wheel payloads), before the bootstrap",
  "// asset map is dropped and the network lockdown applies. Plugin code is",
  "// selected by the harness from the frozen TaskEnvironment — it is never",
  "// reachable from a model-generated import (loadPackage/",
  "// loadPackagesFromImports stay denied forever). Every payload path is",
  "// re-validated here; any invalid path, failed verification or failed smoke",
  "// import THROWS, which fails the whole boot closed: the interpreter never",
  "// reports READY with a declared plugin missing.",
  "async function installExtensionModules(instance) {",
  "  if (!receivedExtensions.length) return;",
  "  // The trusted installer closure loads ONLY when a wheel payload needs it,",
  "  // here in the bootstrap window, from the F04c-verified in-memory set.",
  "  const needsInstaller = receivedExtensions.some((m) => m && Array.isArray(m.wheels) && m.wheels.length);",
  "  if (needsInstaller) await instance.loadPackage('micropip');",
  "  for (const mod of receivedExtensions) {",
  "    if (mod && Array.isArray(mod.wheels) && mod.wheels.length) {",
  "      await installWheelModule(instance, mod);",
  "    } else {",
  "      // LEGACY SYNTHETIC COMPOSITION PATH: source text into site-packages.",
  "      // Capability Composition's synthetic proof — NOT Trusted Plugin",
  "      // Runtime artifact delivery.",
  "      const siteDir = instance.runPython('import sysconfig; sysconfig.get_path(\"purelib\")');",
  "      if (typeof siteDir !== 'string' || !siteDir.startsWith('/')) {",
  "        throw new Error('Locus plugin install: could not resolve the site-packages directory');",
  "      }",
  "      const files = (mod && mod.files) || {};",
  "      for (const rel of Object.keys(files)) {",
  "        if (!rel || rel.startsWith('/') || rel.indexOf('\\\\') !== -1 || rel.split('/').indexOf('..') !== -1) {",
  "          throw new Error('Locus plugin install: invalid payload path: ' + rel);",
  "        }",
  "        const full = siteDir + '/' + rel;",
  "        const dir = full.substring(0, full.lastIndexOf('/'));",
  "        if (dir && dir !== siteDir) instance.FS.mkdirTree(dir);",
  "        instance.FS.writeFile(full, String(files[rel]), { encoding: 'utf8' });",
  "      }",
  "    }",
  "    for (const name of (mod && mod.imports) || []) {",
  "      const moduleName = String(name);",
  "      if (!/^[A-Za-z_][A-Za-z0-9_]*(\\.[A-Za-z_][A-Za-z0-9_]*)*$/.test(moduleName)) {",
  "        throw new Error('Locus plugin install: invalid smoke import name: ' + moduleName);",
  "      }",
  "      try {",
  "        instance.runPython('import ' + moduleName);",
  "      } catch (e) {",
  "        throw new Error('Locus plugin install: smoke import failed for ' + moduleName",
  "          + ' (plugin ' + ((mod && mod.pluginId) || '?') + '): ' + String(e && e.message ? e.message : e));",
  "      }",
  "    }",
  "  }",
  "  if (needsInstaller) await neuterBootstrapInstaller(instance);",
  "}",
  "",
  "// Pyodide is booted lazily on the first run, entirely from the in-memory",
  "// asset set the trusted harness delivered. Bootstrap order is the",
  "// authority boundary: core runtime -> declared packages -> DROP the",
  "// bootstrap resolver's asset map -> NETWORK LOCKDOWN -> ready. No user",
  "// code has executed yet; no network request is possible from this worker",
  "// at any point (the creator CSP sees to that — the resolver only ever",
  "// served memory).",
  "async function ensureLockedPyodide() {",
  "  if (bootPhase === 'locked' && py) return py;",
  "  if (!pyodideLoading) {",
  "    bootPhase = 'booting';",
  "    pyodideLoading = (async () => {",
  "      const assets = await awaitAssets();",
  "      installBootstrapResolver(assets);",
  "      // pyodide.js assigns globalThis.loadPyodide itself.",
  "      (0, eval)(textAsset(assets, 'pyodide.js'));",
  "      // pyodide.asm.js opens with \"use strict\", so its var stays inside",
  "      // the eval scope — export it explicitly. With the factory present,",
  "      // loadPyodide NEVER loads a script itself (no importScripts, no",
  "      // dynamic import): the browser loaders are never invoked.",
  "      (0, eval)(textAsset(assets, 'pyodide.asm.js')",
  "        + '\\n;globalThis._createPyodideModule = _createPyodideModule;');",
  "      const instance = await loadPyodide({",
  "        indexURL: VIRTUAL_BASE,",
  "        lockFileURL: VIRTUAL_BASE + 'pyodide-lock.json',",
  "        stdLibURL: VIRTUAL_BASE + 'python_stdlib.zip',",
  "      });",
  "      await instance.loadPackage(PYTHON_RUNTIME_PACKAGES);",
  "      // TPR v1A / Capability Composition: all enabled Python plugins are",
  "      // verified, installed and smoke-imported here — wheel payloads load",
  "      // the fixed installer closure (micropip) and install OFFLINE from",
  "      // in-memory bytes — all BEFORE the resolver's asset map is dropped",
  "      // and the lockdown applies. After READY, an enabled plugin imports",
  "      // like any preinstalled package, with no Harness RPC and no network.",
  "      await installExtensionModules(instance);",
  "      // Bootstrap authority ends here: the asset map is dropped BEFORE the",
  "      // lockdown, in the same synchronous block — no user code can run in",
  "      // between, and a resolver with an empty map fails closed anyway.",
  "      bootstrapAssets = null;",
  "      lockdownAttempted = true;",
  "      applyNetworkLockdown(instance);",
  "      return instance;",
  "    })();",
  "  }",
  "  try {",
  "    py = await pyodideLoading;",
  "  } catch (e) {",
  "    // A failed bootstrap must not be cached or half-served. Before any",
  "    // lockdown attempt the worker is still pristine: reset so the next run",
  "    // retries from scratch (F14 semantics). AFTER a lockdown attempt the",
  "    // bootstrap primitives themselves are denied — the worker is marked",
  "    // permanently failed and self-destructs (onmessage rethrows uncaught,",
  "    // the shell's worker-fatal handler rebuilds a fresh worker that",
  "    // re-bootstraps and re-locks).",
  "    pyodideLoading = null;",
  "    py = null;",
  "    bootPhase = lockdownAttempted ? 'failed' : 'cold';",
  "    throw e;",
  "  }",
  "  bootPhase = 'locked';",
  "  return py;",
  "}",
  "",
  "function b64ToBytes(b64) {",
  "  const bin = atob(b64);",
  "  const bytes = new Uint8Array(bin.length);",
  "  for (let i = 0; i < bin.length; i++) bytes[i] = bin.charCodeAt(i);",
  "  return bytes;",
  "}",
  "",
  "function bytesToB64(bytes) {",
  "  let bin = '';",
  "  const chunk = 0x8000;",
  "  for (let i = 0; i < bytes.length; i += chunk) {",
  "    bin += String.fromCharCode.apply(null, bytes.subarray(i, i + chunk));",
  "  }",
  "  return btoa(bin);",
  "}",
  "",
  "// Roots whose ENTIRE subtree is owned by the sync protocol and replaced",
  "// wholesale on every run. NEVER rmtree anything else — /, /usr, /home,",
  "// /tmp and Pyodide's own paths are strictly off-limits.",
  "const MANAGED_ROOTS = ['/mnt/workspace', '/mnt/upload', '/mnt/download', '/home/locus'];",
  "// /tmp belongs to Pyodide: syncIn deletes exactly the files AND directories",
  "// IT wrote on the previous run (tracked module-level), never the directory",
  "// itself.",
  "let tmpManagedFiles = [];",
  "let tmpManagedDirs = [];",
  "",
  "function rmTree(root) {",
  "  if (MANAGED_ROOTS.indexOf(root) === -1) throw new Error('refusing to rmtree unmanaged root: ' + root);",
  "  py.runPython('import shutil; shutil.rmtree(' + JSON.stringify(root) + ', ignore_errors=True)');",
  "}",
  "",
  "// Reset each managed mirror root, then write the incoming snapshot:",
  "// directories FIRST (empty dirs are real filesystem state — the shell cwd",
  "// may point at one), then files. Returns a {ABS path: b64} manifest used",
  "// to detect new/changed/deleted files after the run.",
  "function syncIn(mounts) {",
  "  const manifest = {};",
  "  for (const m of mounts || []) {",
  "    const root = m.root;",
  "    if (MANAGED_ROOTS.indexOf(root) !== -1) {",
  "      rmTree(root);",
  "      py.FS.mkdirTree(root);",
  "    } else if (root === '/tmp') {",
  "      for (const p of tmpManagedFiles) { try { py.FS.unlink(p); } catch (e) {} }",
  "      tmpManagedFiles = [];",
  "      // Deepest first; best-effort (a dir with untracked content stays).",
  "      for (const d of tmpManagedDirs.slice().sort().reverse()) { try { py.FS.rmdir(d); } catch (e) {} }",
  "      tmpManagedDirs = [];",
  "    } else {",
  "      continue; // unknown root: never touched",
  "    }",
  "    for (const d of (m.directories || []).slice().sort()) {",
  "      py.FS.mkdirTree(d);",
  "      if (root === '/tmp') tmpManagedDirs.push(d);",
  "    }",
  "    for (const f of m.files || []) {",
  "      const full = f.path; // absolute VFS path",
  "      const dir = full.substring(0, full.lastIndexOf('/'));",
  "      if (dir) py.FS.mkdirTree(dir);",
  "      py.FS.writeFile(full, b64ToBytes(f.b64));",
  "      manifest[full] = f.b64;",
  "      if (root === '/tmp') tmpManagedFiles.push(full);",
  "    }",
  "    if (m.readOnly) {",
  "      // Best-effort read-only mirror: the authoritative enforcement is the",
  "      // main-thread commit phase (changes under read-only roots are never",
  "      // committed), chmod is defence in depth.",
  "      for (const f of m.files || []) {",
  "        try { py.FS.chmod(f.path, 0o444); } catch (e) {}",
  "      }",
  "    }",
  "  }",
  "  return manifest;",
  "}",
  "",
  "// Directory manifest at sync-in time: every mount root, every synced",
  "// directory and every parent of a synced file. Compared against the",
  "// post-run walk to surface created/deleted directories — empty dirs",
  "// included (a file-only diff silently drops them).",
  "function dirManifest(mounts) {",
  "  const dirs = new Set();",
  "  for (const m of mounts || []) {",
  "    const root = m.root;",
  "    dirs.add(root);",
  "    const addWithParents = (p) => {",
  "      let cur = p;",
  "      while (cur && cur !== root && cur.indexOf(root + '/') === 0) {",
  "        dirs.add(cur);",
  "        cur = cur.substring(0, cur.lastIndexOf('/'));",
  "      }",
  "    };",
  "    for (const d of m.directories || []) addWithParents(d);",
  "    for (const f of m.files || []) addWithParents(f.path.substring(0, f.path.lastIndexOf('/')));",
  "  }",
  "  return dirs;",
  "}",
  "",
  "// Output caps, enforced inside the worker BEFORE anything is posted to the",
  "// main thread — a runaway print loop or huge artifact must not OOM the page.",
  "const MAX_STDOUT_CHARS = 1024 * 1024;",
  "const MAX_STDERR_CHARS = 1024 * 1024;",
  "const MAX_OUT_FILES = 200;",
  "const MAX_OUT_TOTAL_BYTES = 25 * 1024 * 1024;",
  "",
  "function walkFs(dir, prefix, out, dirs) {",
  "  for (const entry of py.FS.readdir(dir)) {",
  "    if (entry === '.' || entry === '..') continue;",
  "    const full = dir + '/' + entry;",
  "    const stat = py.FS.stat(full);",
  "    if (py.FS.isDir(stat.mode)) {",
  "      if (dirs) dirs.push(prefix + entry);",
  "      walkFs(full, prefix + entry + '/', out, dirs);",
  "    } else {",
  "      out.push({ path: prefix + entry, full: full, size: stat.size });",
  "    }",
  "  }",
  "}",
  "",
  "function b64Size(b64) {",
  "  const len = b64.length;",
  "  let pad = 0;",
  "  if (b64[len - 1] === '=') pad++;",
  "  if (b64[len - 2] === '=') pad++;",
  "  return Math.floor(len / 4) * 3 - pad;",
  "}",
  "",
  "// Collect the output changeset across ALL mount roots; caps are global",
  "// (shared across mounts). Files that cannot be collected within the caps",
  "// are reported as STRUCTURED uncollected paths — the changeset is then",
  "// incomplete and the main thread must not treat deletions as committable",
  "// (a rename target among the uncollected files would lose the source).",
  "// Sizes are checked via stat BEFORE reading/base64-encoding a file.",
  "// All paths in the result are absolute.",
  "// Directories have no content and no caps: created/deleted dirs are",
  "// diffed against the sync-in directory manifest (empty dirs included).",
  "function diffOut(manifest, beforeDirs, mounts) {",
  "  const changed = [];",
  "  const uncollected = [];",
  "  const present = new Set();",
  "  const afterDirs = new Set();",
  "  let total = 0;",
  "  for (const m of mounts || []) {",
  "    const root = m.root;",
  "    let rootStat = null;",
  "    try { rootStat = py.FS.stat(root); } catch (e) { rootStat = null; }",
  "    if (!rootStat || !py.FS.isDir(rootStat.mode)) continue; // mirror root absent — its files read as deleted",
  "    afterDirs.add(root);",
  "    const entries = [];",
  "    const dirList = [];",
  "    walkFs(root, root + '/', entries, dirList);",
  "    for (const d of dirList) afterDirs.add(d);",
  "    for (const e of entries) {",
  "      present.add(e.path);",
  "      const snapB64 = manifest[e.path];",
  "      const snapSize = snapB64 !== undefined ? b64Size(snapB64) : -1;",
  "      if (snapSize >= 0 && e.size === snapSize) {",
  "        // Possibly unchanged (same size as the sync-in snapshot, which is",
  "        // bounded by the sync-in caps): read and compare to be sure.",
  "        const b64 = bytesToB64(py.FS.readFile(e.full));",
  "        if (snapB64 === b64) continue;",
  "        if (changed.length >= MAX_OUT_FILES || total + e.size > MAX_OUT_TOTAL_BYTES) {",
  "          uncollected.push(e.path);",
  "          continue;",
  "        }",
  "        total += e.size;",
  "        changed.push({ path: e.path, b64: b64 });",
  "        continue;",
  "      }",
  "      // Definitely new or changed (no snapshot, or size differs): check the",
  "      // budget from stat.size BEFORE reading the file into memory.",
  "      if (changed.length >= MAX_OUT_FILES || total + e.size > MAX_OUT_TOTAL_BYTES) {",
  "        uncollected.push(e.path);",
  "        continue;",
  "      }",
  "      total += e.size;",
  "      changed.push({ path: e.path, b64: bytesToB64(py.FS.readFile(e.full)) });",
  "    }",
  "  }",
  "  // Files that were synced in but no longer exist after the run were",
  "  // deleted (or renamed away) by the Python code.",
  "  const deleted = [];",
  "  for (const path of Object.keys(manifest)) {",
  "    if (!present.has(path)) deleted.push(path);",
  "  }",
  "  // Directory diff against the sync-in manifest. Mount roots themselves are",
  "  // protocol-managed, never reported. Deterministic order: creates are",
  "  // parent-first (lexicographic order guarantees it), deletes child-first.",
  "  const roots = new Set();",
  "  for (const m of mounts || []) roots.add(m.root);",
  "  const createdDirs = [];",
  "  for (const d of afterDirs) {",
  "    if (!beforeDirs.has(d) && !roots.has(d)) createdDirs.push(d);",
  "  }",
  "  createdDirs.sort();",
  "  const deletedDirs = [];",
  "  for (const d of beforeDirs) {",
  "    if (!afterDirs.has(d) && !roots.has(d)) deletedDirs.push(d);",
  "  }",
  "  deletedDirs.sort().reverse();",
  "  return { changed: changed, deleted: deleted, uncollected: uncollected,",
  "    createdDirs: createdDirs, deletedDirs: deletedDirs };",
  "}",
  "",
  "self.onmessage = async (ev) => {",
  "  const msg = ev.data || {};",
  "  if (msg.cmd === 'bootstrap') {",
  "    // Trusted harness phase: the fixed asset set arrives by postMessage.",
  "    // Idempotent — a repeat delivery while locked just re-acknowledges;",
  "    // while booting it is ignored (the boot consumes the first set).",
  "    if (receivedAssets) {",
  "      self.postMessage({ id: msg.id, type: 'boot', status: bootPhase === 'locked' ? 'locked' : 'pending' });",
  "      return;",
  "    }",
  "    receivedAssets = msg.assets || {};",
  "    receivedExtensions = Array.isArray(msg.extensionModules) ? msg.extensionModules : [];",
  "    if (assetsResolve) { const r = assetsResolve; assetsResolve = null; assetsWaiter = null; r(receivedAssets); }",
  "    try {",
  "      await ensureLockedPyodide();",
  "      self.postMessage({ id: msg.id, type: 'boot', status: 'locked' });",
  "    } catch (e) {",
  "      self.postMessage({ id: msg.id, type: 'boot', error: String(e && e.message ? e.message : e) });",
  "      if (bootPhase === 'failed') {",
  "        // Uncaught worker error -> creator relay -> shell rebuild.",
  "        setTimeout(() => { throw new Error('Python worker failed to apply the network lockdown'); }, 0);",
  "      }",
  "    }",
  "    return;",
  "  }",
  "  if (msg.cmd !== 'run') return;",
  "  const id = msg.id;",
  "  if (bootPhase === 'failed') {",
  "    self.postMessage({ id: id, type: 'result', stdout: '', stderr: '', error: 'Python worker failed to apply the network lockdown', files: [], deleted: [], createdDirs: [], deletedDirs: [], uncollectedFiles: [], stdoutTruncated: false, stderrTruncated: false });",
  "    return;",
  "  }",
  "  try {",
  "    self.postMessage({ id: id, type: 'status', status: 'loading' });",
  "    // If the run arrived before the bootstrap message, this await holds it",
  "    // until the assets land (the shell always delivers bootstrap first; a",
  "    // lost bootstrap surfaces as the shell's run timeout).",
  "    await ensureLockedPyodide();",
  "    self.postMessage({ id: id, type: 'status', status: 'ready' });",
  "",
  "    const manifest = syncIn(msg.mounts || []);",
  "    const beforeDirs = dirManifest(msg.mounts || []);",
  "",
  "    let stdout = '';",
  "    let stderr = '';",
  "    let stdoutTruncated = false;",
  "    let stderrTruncated = false;",
  "    py.setStdout({ batched: (s) => {",
  "      if (stdoutTruncated) return;",
  "      stdout += s + '\\n';",
  "      if (stdout.length > MAX_STDOUT_CHARS) {",
  "        stdout = stdout.slice(0, MAX_STDOUT_CHARS);",
  "        stdoutTruncated = true;",
  "      }",
  "    } });",
  "    py.setStderr({ batched: (s) => {",
  "      if (stderrTruncated) return;",
  "      stderr += s + '\\n';",
  "      if (stderr.length > MAX_STDERR_CHARS) {",
  "        stderr = stderr.slice(0, MAX_STDERR_CHARS);",
  "        stderrTruncated = true;",
  "      }",
  "    } });",
  "",
  "    let error = null;",
  "    try {",
  "      // Python runs with the SAME absolute cwd as the shell invocation.",
  "      // Imports are deliberately NOT auto-loaded here: package downloads",
  "      // are a bootstrap-time harness decision (PYTHON_RUNTIME_PACKAGES),",
  "      // never a side effect of model-generated imports. An import the",
  "      // runtime does not carry fails honestly (ModuleNotFoundError) with",
  "      // no network attempt.",
  "      await py.runPythonAsync('import os\\nos.chdir(' + JSON.stringify(msg.cwd || '/home/locus') + ')');",
  "      await py.runPythonAsync(msg.code);",
  "    } catch (e) {",
  "      // PythonError messages carry the full traceback.",
  "      error = String(e && e.message ? e.message : e);",
  "    }",
  "",
  "    const diff = diffOut(manifest, beforeDirs, msg.mounts || []);",
  "    self.postMessage({",
  "      id: id, type: 'result', stdout: stdout, stderr: stderr, error: error,",
  "      files: diff.changed, deleted: diff.deleted,",
  "      createdDirs: diff.createdDirs, deletedDirs: diff.deletedDirs,",
  "      uncollectedFiles: diff.uncollected,",
  "      stdoutTruncated: stdoutTruncated, stderrTruncated: stderrTruncated,",
  "    });",
  "  } catch (e) {",
  "    self.postMessage({ id: id, type: 'result', stdout: '', stderr: '', error: String(e && e.message ? e.message : e), files: [], deleted: [], createdDirs: [], deletedDirs: [], uncollectedFiles: [], stdoutTruncated: false, stderrTruncated: false });",
  "    if (bootPhase === 'failed') {",
  "      // Uncaught worker error -> shell worker.onerror -> terminate + rebuild.",
  "      setTimeout(() => { throw new Error('Python worker failed to apply the network lockdown'); }, 0);",
  "    }",
  "  }",
  "};",
  "",
].join(String.fromCharCode(10));

export const GREP_WORKER_SOURCE = [
  "",
  "// ============================================================",
  "//  GREP REGEX WORKER — untrusted-pattern compute containment.",
  "//  The grep pattern is model-controlled: RegExp compilation and",
  "//  every match run HERE, never on the main thread, so a",
  "//  catastrophic-backtracking pattern burns this worker (which the",
  "//  shell terminates at the hard timeout, on cancellation, and at",
  "//  the command boundary) instead of freezing the UI event loop.",
  "//  Pure compute: no network, no filesystem, no DOM, no persistence.",
  "//",
  "//  Message in:  { id, cmd: 'init', pattern, flags }",
  "//  Reply out:   { id, type: 'ready' } | { id, type: 'invalid_pattern' }",
  "//",
  "//  Message in:  { id, cmd: 'scan', text, countOnly, maxMatches }",
  "//  Reply out:   countOnly → { id, type: 'result', count }",
  "//               otherwise → { id, type: 'result',",
  "//                             matches: [{ lineNumber, line }],",
  "//                             hitMatchLimit }",
  "//  Every request gets exactly one reply carrying the same id; a",
  "//  request that cannot be honored replies 'internal_error'. Raw",
  "//  patterns and error strings never leave this worker.",
  "// ============================================================",
  "",
  "let re = null;",
  "",
  "// Line-splitting parity with the shell's splitLines(): '\\n' separators,",
  "// and a trailing newline is a terminator, not an empty final line.",
  "function splitLines(text) {",
  "  const lines = String(text).split('\\n');",
  "  if (lines.length && lines[lines.length - 1] === '') lines.pop();",
  "  return lines;",
  "}",
  "",
  "self.onmessage = (ev) => {",
  "  const msg = (ev && ev.data) || {};",
  "  try {",
  "    if (msg.cmd === 'init') {",
  "      try {",
  "        re = new RegExp(String(msg.pattern), msg.flags ? String(msg.flags) : '');",
  "      } catch (e) {",
  "        re = null;",
  "        self.postMessage({ id: msg.id, type: 'invalid_pattern' });",
  "        return;",
  "      }",
  "      self.postMessage({ id: msg.id, type: 'ready' });",
  "      return;",
  "    }",
  "    if (msg.cmd === 'scan') {",
  "      if (!re) {",
  "        self.postMessage({ id: msg.id, type: 'internal_error' });",
  "        return;",
  "      }",
  "      const lines = splitLines(msg.text);",
  "      if (msg.countOnly) {",
  "        // Count mode answers the TRUE number of matching lines: the",
  "        // GREP_MAX_MATCHES presentation cap never applies here.",
  "        let count = 0;",
  "        for (let i = 0; i < lines.length; i++) {",
  "          if (re.test(lines[i])) count++;",
  "        }",
  "        self.postMessage({ id: msg.id, type: 'result', count: count });",
  "        return;",
  "      }",
  "      const budget = typeof msg.maxMatches === 'number' ? msg.maxMatches : Infinity;",
  "      const matches = [];",
  "      let hitMatchLimit = false;",
  "      for (let i = 0; i < lines.length; i++) {",
  "        if (matches.length >= budget) { hitMatchLimit = true; break; }",
  "        if (re.test(lines[i])) matches.push({ lineNumber: i + 1, line: lines[i] });",
  "      }",
  "      self.postMessage({ id: msg.id, type: 'result', matches: matches, hitMatchLimit: hitMatchLimit });",
  "      return;",
  "    }",
  "    self.postMessage({ id: msg.id, type: 'internal_error' });",
  "  } catch (e) {",
  "    self.postMessage({ id: msg.id, type: 'internal_error' });",
  "  }",
  "};",
  "",
].join(String.fromCharCode(10));
